services: 
  db4:
    image: postgres
    container_name: db4
    restart: always
    volumes:
      - ./pro.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartaglobal

  compose5:
    image: jorge2091/docker-app
    container_name: compose5
    restart: always
    ports:
      - "2500:80"
    links:
      - db4
    environment: 
      - POSTGRES=postgres://db4:5432
    depends_on:
      - db4
