services: 
  db11:
    image: postgres:10.23-alpine
    container_name: db11
    restart: always
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartaglobal

  compose11:
    image: jorge2091/docker-app5
    container_name: compose11
    restart: always
    ports:
      - "80:80"
    links:
      - db11
    environment: 
      - POSTGRES=postgres://db11:5432
    depends_on:
      - db11
