services: 
  db4:
    image: postgres
    container_name: db4
    restart: always
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartaglobal

  compose5:
    image: jorge2091/docker-app
    container_name: compose5
    restart: always
    ports:
      - "80:80"
    links:
      - db4
    environment: 
      - POSTGRES=postgres://db4:5432
    depends_on:
      - db4
