services: 
  db:
    image: postgres:10.23-alpine
    container_name: db
    restart: always
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartaglobal

  compose:
    image: jorge2091/docker-app5
    container_name: compose
    restart: always
    ports:
      - "80:80"
    links:
      - db
    environment: 
      - POSTGRES=postgres://db:5432
    depends_on:
      - db
